# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
      - run:
          name: Set global environment variables
          command: >
            echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' | sudo tee -a /etc/environment
            source /etc/environment
            \;
      - run: java -version
      - run: ls
      - run: flutter doctor
      - run: flutter test
      - run:
          command: flutter build apk --release
          working_directory: example
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
