# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - checkout
      - run: ls
      - run: flutter doctor
      - run: flutter test
      - name: Setup Java JDK
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '11'
      - run: 
          command: flutter build apk --release
          working_directory: example
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          
  
  

